<a href="https://colab.research.google.com/github/WesleyMaciel2510/cursos/blob/main/Copy_of_CursoSQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Conexão

Importar a biblioteca

In [ ]:
import sqlite3
import pandas as pd

#Criação do banco de dados

In [ ]:
conexao = sqlite3.connect('AULA')

Apontar para o banco de dados

In [ ]:
cursor = conexao.cursor()

#Criação das tabelas

Tabela Cliente:

```
CREATE TABLE Cliente (
    IDCliente INT PRIMARY KEY,
    Nome VARCHAR(100),
    NumeroComentarios INT,
    NumeroLikes INT,
    Localizacao VARCHAR(100),
    Genero VARCHAR(20)
);
```

In [ ]:
cliente_sql = "CREATE TABLE Cliente (IDCliente INT PRIMARY KEY, Nome VARCHAR(100), NumeroComentarios INT, NumeroLikes INT, Localizacao VARCHAR(100), Genero VARCHAR(20));"

In [ ]:
cursor.execute(cliente_sql)

Tabela Comentario:

```
CREATE TABLE Comentario (
    IDComentario INT PRIMARY KEY,
    TextoOriginal TEXT,
    TextoTraduzido TEXT,
    TituloOriginal VARCHAR(200),
    TituloTraduzido VARCHAR(200),
    IdiomaTexto VARCHAR(50),
    DataPublicacao DATE,
    NumeroLikes INT,
    Avaliacao INT,
    URL VARCHAR(100),
    IDCliente INT,
    FOREIGN KEY (IDCliente) REFERENCES Cliente(IDCliente),
);
```

In [ ]:
comentario_sql = "CREATE TABLE Comentario (IDComentario INT PRIMARY KEY, TextoOriginal TEXT, TextoTraduzido TEXT, TituloOriginal VARCHAR(200), TituloTraduzido VARCHAR(200), IdiomaTexto VARCHAR(50), DataPublicacao DATE, NumeroLikes INT, Avaliacao INT, URL VARCHAR(100), IDCliente INT, FOREIGN KEY (IDCliente) REFERENCES Cliente(IDCliente));"

In [ ]:
cursor.execute(comentario_sql)

In [ ]:
conexao.commit()

#Inserção dos Dados

## Tabela Clientes

In [ ]:
cliente1 = "INSERT INTO Cliente (IDCliente, Nome, NumeroComentarios, NumeroLikes, Localizacao, Genero) VALUES (1, 'Ana Silva', 15, 120, 'São Paulo', 'Feminino');"
cliente2 = "INSERT INTO Cliente (IDCliente, Nome, NumeroComentarios, NumeroLikes, Localizacao, Genero) VALUES (2, 'Carlos Souza', 8, 45, 'Rio de Janeiro', 'Masculino');"
cliente3 = "INSERT INTO Cliente (IDCliente, Nome, NumeroComentarios, NumeroLikes, Localizacao, Genero) VALUES (3, 'Maria Oliveira', 22, 210, 'Belo Horizonte', 'Feminino');"
cliente4 = "INSERT INTO Cliente (IDCliente, Nome, NumeroComentarios, NumeroLikes, Localizacao, Genero) VALUES (4, 'Pedro Costa', 5, 30, 'Curitiba', 'Masculino');"
cliente5 = "INSERT INTO Cliente (IDCliente, Nome, NumeroComentarios, NumeroLikes, Localizacao, Genero) VALUES (5, 'Fernanda Lima', 10, 80, 'Porto Alegre', 'Feminino');"
cliente6 = "INSERT INTO Cliente (IDCliente, Nome, NumeroComentarios, NumeroLikes, Localizacao, Genero) VALUES (6, 'João Almeida', 18, 150, 'Recife', 'Masculino');"
cliente7 = "INSERT INTO Cliente (IDCliente, Nome, NumeroComentarios, NumeroLikes, Localizacao, Genero) VALUES (7, 'Mariana Santos', 12, 95, 'Salvador', 'Feminino');"
cliente8 = "INSERT INTO Cliente (IDCliente, Nome, NumeroComentarios, NumeroLikes, Localizacao, Genero) VALUES (8, 'Rafael Ferreira', 7, 60, 'Brasília', 'Masculino');"
cliente9 = "INSERT INTO Cliente (IDCliente, Nome, NumeroComentarios, NumeroLikes, Localizacao, Genero) VALUES (9, 'Patrícia Araujo', 20, 175, 'Fortaleza', 'Feminino');"
cliente10 = "INSERT INTO Cliente (IDCliente, Nome, NumeroComentarios, NumeroLikes, Localizacao, Genero) VALUES (10, 'Luiz Mendes', 25, 200, 'Manaus', 'Masculino');"

In [ ]:
cursor.execute(cliente1)
cursor.execute(cliente2)
cursor.execute(cliente3)
cursor.execute(cliente4)
cursor.execute(cliente5)
cursor.execute(cliente6)
cursor.execute(cliente7)
cursor.execute(cliente8)
cursor.execute(cliente9)
cursor.execute(cliente10)

## Tabela Comentario

In [ ]:
comentario1 = "INSERT INTO Comentario (IDComentario, TextoOriginal, TextoTraduzido, TituloOriginal, TituloTraduzido, IdiomaTexto, DataPublicacao, NumeroLikes, Avaliacao, URL, IDCliente) VALUES (1, 'Ótimo atendimento e comida deliciosa!', 'Great service and delicious food!', 'Experiência Incrível', 'Amazing Experience', 'Português', '2023-01-15', 35, 5, 'http://example.com/comentario1', 1);"
comentario2 = "INSERT INTO Comentario (IDComentario, TextoOriginal, TextoTraduzido, TituloOriginal, TituloTraduzido, IdiomaTexto, DataPublicacao, NumeroLikes, Avaliacao, URL, IDCliente) VALUES (2, 'Ambiente agradável e preços justos.', 'Pleasant environment and fair prices.', 'Ambiente Confortável', 'Comfortable Environment', 'Português', '2023-02-10', 50, 4, 'http://example.com/comentario2', 2);"
comentario3 = "INSERT INTO Comentario (IDComentario, TextoOriginal, TextoTraduzido, TituloOriginal, TituloTraduzido, IdiomaTexto, DataPublicacao, NumeroLikes, Avaliacao, URL, IDCliente) VALUES (3, 'A comida estava fria e sem sabor.', 'The food was cold and tasteless.', 'Decepcionante', 'Disappointing', 'Português', '2023-03-05', 10, 2, 'http://example.com/comentario3', 3);"
comentario4 = "INSERT INTO Comentario (IDComentario, TextoOriginal, TextoTraduzido, TituloOriginal, TituloTraduzido, IdiomaTexto, DataPublicacao, NumeroLikes, Avaliacao, URL, IDCliente) VALUES (4, 'Excelente variedade de pratos.', 'Excellent variety of dishes.', 'Muitas Opções', 'Many Options', 'Português', '2023-04-01', 40, 5, 'http://example.com/comentario4', 4);"
comentario5 = "INSERT INTO Comentario (IDComentario, TextoOriginal, TextoTraduzido, TituloOriginal, TituloTraduzido, IdiomaTexto, DataPublicacao, NumeroLikes, Avaliacao, URL, IDCliente) VALUES (5, 'Demora no atendimento.', 'Delay in service.', 'Atendimento Demorado', 'Slow Service', 'Português', '2023-05-20', 5, 2, 'http://example.com/comentario5', 5);"
comentario6 = "INSERT INTO Comentario (IDComentario, TextoOriginal, TextoTraduzido, TituloOriginal, TituloTraduzido, IdiomaTexto, DataPublicacao, NumeroLikes, Avaliacao, URL, IDCliente) VALUES (6, 'Sobremesas maravilhosas!', 'Wonderful desserts!', 'Sobremesas', 'Desserts', 'Português', '2023-06-11', 60, 5, 'http://example.com/comentario6', 6);"
comentario7 = "INSERT INTO Comentario (IDComentario, TextoOriginal, TextoTraduzido, TituloOriginal, TituloTraduzido, IdiomaTexto, DataPublicacao, NumeroLikes, Avaliacao, URL, IDCliente) VALUES (7, 'Porções pequenas pelo preço.', 'Small portions for the price.', 'Porções Pequenas', 'Small Portions', 'Português', '2023-07-18', 15, 3, 'http://example.com/comentario7', 7);"
comentario8 = "INSERT INTO Comentario (IDComentario, TextoOriginal, TextoTraduzido, TituloOriginal, TituloTraduzido, IdiomaTexto, DataPublicacao, NumeroLikes, Avaliacao, URL, IDCliente) VALUES (8, 'Ótima opção para vegetarianos.', 'Great option for vegetarians.', 'Opção Vegetariana', 'Vegetarian Option', 'Português', '2023-08-24', 25, 4, 'http://example.com/comentario8', 8);"
comentario9 = "INSERT INTO Comentario (IDComentario, TextoOriginal, TextoTraduzido, TituloOriginal, TituloTraduzido, IdiomaTexto, DataPublicacao, NumeroLikes, Avaliacao, URL, IDCliente) VALUES (9, 'Música ao vivo excelente!', 'Excellent live music!', 'Música Ao Vivo', 'Live Music', 'Português', '2023-09-30', 70, 5, 'http://example.com/comentario9', 9);"
comentario10 = "INSERT INTO Comentario (IDComentario, TextoOriginal, TextoTraduzido, TituloOriginal, TituloTraduzido, IdiomaTexto, DataPublicacao, NumeroLikes, Avaliacao, URL, IDCliente) VALUES (10, 'Lugar muito barulhento.', 'Very noisy place.', 'Muito Barulho', 'Very Noisy', 'Português', '2023-10-12', 8, 2, 'http://example.com/comentario10', 10);"
comentario11 = "INSERT INTO Comentario (IDComentario, TextoOriginal, TextoTraduzido, TituloOriginal, TituloTraduzido, IdiomaTexto, DataPublicacao, NumeroLikes, Avaliacao, URL, IDCliente) VALUES (11, 'Atendimento personalizado e simpático.', 'Personalized and friendly service.', 'Atendimento Excelente', 'Excellent Service', 'Português', '2023-01-20', 65, 5, 'http://example.com/comentario11', 1);"
comentario12 = "INSERT INTO Comentario (IDComentario, TextoOriginal, TextoTraduzido, TituloOriginal, TituloTraduzido, IdiomaTexto, DataPublicacao, NumeroLikes, Avaliacao, URL, IDCliente) VALUES (12, 'Localização privilegiada e ambiente sofisticado.', 'Prime location and sophisticated environment.', 'Ambiente Sofisticado', 'Sophisticated Environment', 'Português', '2023-02-25', 55, 5, 'http://example.com/comentario12', 2);"
comentario13 = "INSERT INTO Comentario (IDComentario, TextoOriginal, TextoTraduzido, TituloOriginal, TituloTraduzido, IdiomaTexto, DataPublicacao, NumeroLikes, Avaliacao, URL, IDCliente) VALUES (13, 'Preço elevado para a qualidade oferecida.', 'High price for the quality offered.', 'Preço Alto', 'High Price', 'Português', '2023-03-15', 12, 3, 'http://example.com/comentario13', 3);"
comentario14 = "INSERT INTO Comentario (IDComentario, TextoOriginal, TextoTraduzido, TituloOriginal, TituloTraduzido, IdiomaTexto, DataPublicacao, NumeroLikes, Avaliacao, URL, IDCliente) VALUES (14, 'Carta de vinhos excepcional.', 'Exceptional wine list.', 'Carta de Vinhos', 'Wine List', 'Português', '2023-04-10', 45, 5, 'http://example.com/comentario14', 4);"
comentario15 = "INSERT INTO Comentario (IDComentario, TextoOriginal, TextoTraduzido, TituloOriginal, TituloTraduzido, IdiomaTexto, DataPublicacao, NumeroLikes, Avaliacao, URL, IDCliente) VALUES (15, 'Garçons despreparados.', 'Unprepared waiters.', 'Atendimento Ruim', 'Bad Service', 'Português', '2023-05-05', 20, 2, 'http://example.com/comentario15', 5);"
comentario16 = "INSERT INTO Comentario (IDComentario, TextoOriginal, TextoTraduzido, TituloOriginal, TituloTraduzido, IdiomaTexto, DataPublicacao, NumeroLikes, Avaliacao, URL, IDCliente) VALUES (16, 'Buffet variado e bem servido.', 'Varied and well-served buffet.', 'Buffet Variado', 'Varied Buffet', 'Português', '2023-06-22', 30, 4, 'http://example.com/comentario16', 6);"
comentario17 = "INSERT INTO Comentario (IDComentario, TextoOriginal, TextoTraduzido, TituloOriginal, TituloTraduzido, IdiomaTexto, DataPublicacao, NumeroLikes, Avaliacao, URL, IDCliente) VALUES (17, 'Restaurante acessível para cadeirantes.', 'Wheelchair accessible restaurant.', 'Acessibilidade', 'Accessibility', 'Português', '2023-07-15', 18, 4, 'http://example.com/comentario17', 7);"
comentario18 = "INSERT INTO Comentario (IDComentario, TextoOriginal, TextoTraduzido, TituloOriginal, TituloTraduzido, IdiomaTexto, DataPublicacao, NumeroLikes, Avaliacao, URL, IDCliente) VALUES (18, 'Demorou muito para trazerem os pratos.', 'It took a long time to bring the dishes.', 'Demora nos Pratos', 'Delay in Dishes', 'Português', '2023-08-18', 7, 2, 'http://example.com/comentario18', 8);"
comentario19 = "INSERT INTO Comentario (IDComentario, TextoOriginal, TextoTraduzido, TituloOriginal, TituloTraduzido, IdiomaTexto, DataPublicacao, NumeroLikes, Avaliacao, URL, IDCliente) VALUES (19, 'Menu infantil muito bom.', 'Very good kids menu.', 'Menu Infantil', 'Kids Menu', 'Português', '2023-09-10', 22, 5, 'http://example.com/comentario19', 9);"
comentario20 = "INSERT INTO Comentario (IDComentario, TextoOriginal, TextoTraduzido, TituloOriginal, TituloTraduzido, IdiomaTexto, DataPublicacao, NumeroLikes, Avaliacao, URL, IDCliente) VALUES (20, 'Serviço de reserva eficiente.', 'Efficient reservation service.', 'Reserva Eficiente', 'Efficient Reservation', 'Português', '2023-10-05', 28, 4, 'http://example.com/comentario20', 10);"

In [ ]:
cursor.execute(comentario1)
cursor.execute(comentario2)
cursor.execute(comentario3)
cursor.execute(comentario4)
cursor.execute(comentario5)
cursor.execute(comentario6)
cursor.execute(comentario7)
cursor.execute(comentario8)
cursor.execute(comentario9)
cursor.execute(comentario10)
cursor.execute(comentario11)
cursor.execute(comentario12)
cursor.execute(comentario13)
cursor.execute(comentario14)
cursor.execute(comentario15)
cursor.execute(comentario16)
cursor.execute(comentario17)
cursor.execute(comentario18)
cursor.execute(comentario19)
cursor.execute(comentario20)

#Consulta Tabelas - Operador `SELECT`

Tabela Cliente

In [ ]:
consulta = "SELECT * FROM Cliente;"

In [ ]:
consulta_sql = cursor.execute(consulta).fetchall()

In [ ]:
for i in consulta_sql:
  print(i)

(1, 'Ana Silva', 15, 120, 'São Paulo', 'Feminino')
(2, 'Carlos Souza', 8, 45, 'Rio de Janeiro', 'Masculino')
(3, 'Maria Oliveira', 22, 210, 'Belo Horizonte', 'Feminino')
(4, 'Pedro Costa', 5, 30, 'Curitiba', 'Masculino')
(5, 'Fernanda Lima', 10, 80, 'Porto Alegre', 'Feminino')
(6, 'João Almeida', 18, 150, 'Recife', 'Masculino')
(7, 'Mariana Santos', 12, 95, 'Salvador', 'Feminino')
(8, 'Rafael Ferreira', 7, 60, 'Brasília', 'Masculino')
(9, 'Patrícia Araujo', 20, 175, 'Fortaleza', 'Feminino')
(10, 'Luiz Mendes', 25, 200, 'Manaus', 'Masculino')

In [ ]:
df_cliente = pd.read_sql_query(consulta, conexao)

In [ ]:
df_cliente

,IDCliente,Nome,NumeroComentarios,NumeroLikes,Localizacao,Genero
0,1,Ana Silva,15,120,São Paulo,Feminino
1,2,Carlos Souza,8,45,Rio de Janeiro,Masculino
2,3,Maria Oliveira,22,210,Belo Horizonte,Feminino
3,4,Pedro Costa,5,30,Curitiba,Masculino
4,5,Fernanda Lima,10,80,Porto Alegre,Feminino
5,6,João Almeida,18,150,Recife,Masculino
6,7,Mariana Santos,12,95,Salvador,Feminino
7,8,Rafael Ferreira,7,60,Brasília,Masculino
8,9,Patrícia Araujo,20,175,Fortaleza,Feminino
9,10,Luiz Mendes,25,200,Manaus,Masculino

Table Comentario

In [ ]:
consulta = "SELECT * FROM Comentario;"

In [ ]:
consulta_sql = cursor.execute(consulta).fetchall()

In [ ]:
for i in consulta_sql:
  print(i)

(1, 'Ótimo atendimento e comida deliciosa!', 'Great service and delicious food!', 'Experiência Incrível', 'Amazing Experience', 'Português', '2023-01-15', 35, 5, 'http://example.com/comentario1', 1)
(2, 'Ambiente agradável e preços justos.', 'Pleasant environment and fair prices.', 'Ambiente Confortável', 'Comfortable Environment', 'Português', '2023-02-10', 50, 4, 'http://example.com/comentario2', 2)
(3, 'A comida estava fria e sem sabor.', 'The food was cold and tasteless.', 'Decepcionante', 'Disappointing', 'Português', '2023-03-05', 10, 2, 'http://example.com/comentario3', 3)
(4, 'Excelente variedade de pratos.', 'Excellent variety of dishes.', 'Muitas Opções', 'Many Options', 'Português', '2023-04-01', 40, 5, 'http://example.com/comentario4', 4)
(5, 'Demora no atendimento.', 'Delay in service.', 'Atendimento Demorado', 'Slow Service', 'Português', '2023-05-20', 5, 2, 'http://example.com/comentario5', 5)
(6, 'Sobremesas maravilhosas!', 'Wonderful desserts!', 'Sobremesas', 'Desserts', 'Português', '2023-06-11', 60, 5, 'http://example.com/comentario6', 6)
(7, 'Porções pequenas pelo preço.', 'Small portions for the price.', 'Porções Pequenas', 'Small Portions', 'Português', '2023-07-18', 15, 3, 'http://example.com/comentario7', 7)
(8, 'Ótima opção para vegetarianos.', 'Great option for vegetarians.', 'Opção Vegetariana', 'Vegetarian Option', 'Português', '2023-08-24', 25, 4, 'http://example.com/comentario8', 8)
(9, 'Música ao vivo excelente!', 'Excellent live music!', 'Música Ao Vivo', 'Live Music', 'Português', '2023-09-30', 70, 5, 'http://example.com/comentario9', 9)
(10, 'Lugar muito barulhento.', 'Very noisy place.', 'Muito Barulho', 'Very Noisy', 'Português', '2023-10-12', 8, 2, 'http://example.com/comentario10', 10)
(11, 'Atendimento personalizado e simpático.', 'Personalized and friendly service.', 'Atendimento Excelente', 'Excellent Service', 'Português', '2023-01-20', 65, 5, 'http://example.com/comentario11', 1)
(12, 'Localização privilegiada e ambiente sofisticado.', 'Prime location and sophisticated environment.', 'Ambiente Sofisticado', 'Sophisticated Environment', 'Português', '2023-02-25', 55, 5, 'http://example.com/comentario12', 2)
(13, 'Preço elevado para a qualidade oferecida.', 'High price for the quality offered.', 'Preço Alto', 'High Price', 'Português', '2023-03-15', 12, 3, 'http://example.com/comentario13', 3)
(14, 'Carta de vinhos excepcional.', 'Exceptional wine list.', 'Carta de Vinhos', 'Wine List', 'Português', '2023-04-10', 45, 5, 'http://example.com/comentario14', 4)
(15, 'Garçons despreparados.', 'Unprepared waiters.', 'Atendimento Ruim', 'Bad Service', 'Português', '2023-05-05', 20, 2, 'http://example.com/comentario15', 5)
(16, 'Buffet variado e bem servido.', 'Varied and well-served buffet.', 'Buffet Variado', 'Varied Buffet', 'Português', '2023-06-22', 30, 4, 'http://example.com/comentario16', 6)
(17, 'Restaurante acessível para cadeirantes.', 'Wheelchair accessible restaurant.', 'Acessibilidade', 'Accessibility', 'Português', '2023-07-15', 18, 4, 'http://example.com/comentario17', 7)
(18, 'Demorou muito para trazerem os pratos.', 'It took a long time to bring the dishes.', 'Demora nos Pratos', 'Delay in Dishes', 'Português', '2023-08-18', 7, 2, 'http://example.com/comentario18', 8)
(19, 'Menu infantil muito bom.', 'Very good kids menu.', 'Menu Infantil', 'Kids Menu', 'Português', '2023-09-10', 22, 5, 'http://example.com/comentario19', 9)
(20, 'Serviço de reserva eficiente.', 'Efficient reservation service.', 'Reserva Eficiente', 'Efficient Reservation', 'Português', '2023-10-05', 28, 4, 'http://example.com/comentario20', 10)

In [ ]:
df_comentario = pd.read_sql_query(consulta, conexao)

In [ ]:
df_comentario

,IDComentario,TextoOriginal,TextoTraduzido,TituloOriginal,TituloTraduzido,IdiomaTexto,DataPublicacao,NumeroLikes,Avaliacao,URL,IDCliente
0,1,Ótimo atendimento e comida deliciosa!,Great service and delicious food!,Experiência Incrível,Amazing Experience,Português,2023-01-15,35,5,http://example.com/comentario1,1
1,2,Ambiente agradável e preços justos.,Pleasant environment and fair prices.,Ambiente Confortável,Comfortable Environment,Português,2023-02-10,50,4,http://example.com/comentario2,2
2,3,A comida estava fria e sem sabor.,The food was cold and tasteless.,Decepcionante,Disappointing,Português,2023-03-05,10,2,http://example.com/comentario3,3
3,4,Excelente variedade de pratos.,Excellent variety of dishes.,Muitas Opções,Many Options,Português,2023-04-01,40,5,http://example.com/comentario4,4
4,5,Demora no atendimento.,Delay in service.,Atendimento Demorado,Slow Service,Português,2023-05-20,5,2,http://example.com/comentario5,5
5,6,Sobremesas maravilhosas!,Wonderful desserts!,Sobremesas,Desserts,Português,2023-06-11,60,5,http://example.com/comentario6,6
6,7,Porções pequenas pelo preço.,Small portions for the price.,Porções Pequenas,Small Portions,Português,2023-07-18,15,3,http://example.com/comentario7,7
7,8,Ótima opção para vegetarianos.,Great option for vegetarians.,Opção Vegetariana,Vegetarian Option,Português,2023-08-24,25,4,http://example.com/comentario8,8
8,9,Música ao vivo excelente!,Excellent live music!,Música Ao Vivo,Live Music,Português,2023-09-30,70,5,http://example.com/comentario9,9
9,10,Lugar muito barulhento.,Very noisy place.,Muito Barulho,Very Noisy,Português,2023-10-12,8,2,http://example.com/comentario10,10
10,11,Atendimento personalizado e simpático.,Personalized and friendly service.,Atendimento Excelente,Excellent Service,Português,2023-01-20,65,5,http://example.com/comentario11,1
11,12,Localização privilegiada e ambiente sofisticado.,Prime location and sophisticated environment.,Ambiente Sofisticado,Sophisticated Environment,Português,2023-02-25,55,5,http://example.com/comentario12,2
12,13,Preço elevado para a qualidade oferecida.,High price for the quality offered.,Preço Alto,High Price,Português,2023-03-15,12,3,http://example.com/comentario13,3
13,14,Carta de vinhos excepcional.,Exceptional wine list.,Carta de Vinhos,Wine List,Português,2023-04-10,45,5,http://example.com/comentario14,4
14,15,Garçons despreparados.,Unprepared waiters.,Atendimento Ruim,Bad Service,Português,2023-05-05,20,2,http://example.com/comentario15,5
15,16,Buffet variado e bem servido.,Varied and well-served buffet.,Buffet Variado,Varied Buffet,Português,2023-06-22,30,4,http://example.com/comentario16,6
16,17,Restaurante acessível para cadeirantes.,Wheelchair accessible restaurant.,Acessibilidade,Accessibility,Português,2023-07-15,18,4,http://example.com/comentario17,7
17,18,Demorou muito para trazerem os pratos.,It took a long time to bring the dishes.,Demora nos Pratos,Delay in Dishes,Português,2023-08-18,7,2,http://example.com/comentario18,8
18,19,Menu infantil muito bom.,Very good kids menu.,Menu Infantil,Kids Menu,Português,2023-09-10,22,5,http://example.com/comentario19,9
19,20,Serviço de reserva eficiente.,Efficient reservation service.,Reserva Eficiente,Efficient Reservation,Português,2023-10-05,28,4,http://example.com/comentario20,10

#Operador `WHERE`

O operador `where` é utilizado para "filtrar" registros da consulta.

Lista de operadores:

* '='
* '>'
* '<'
* '>='
* '<='
* '<>'
* 'BETWEEN'
* 'LIKE'
* 'IN'

##Operador Relacional

In [ ]:
consulta = "SELECT Nome from Cliente where NumeroComentarios > 20;"

In [ ]:
consulta_sql = cursor.execute(consulta).fetchall()

In [ ]:
consulta_sql

[('Maria Oliveira',), ('Luiz Mendes',)]

## Operador `BETWEEN`

In [ ]:
consulta = "SELECT Nome, NumeroComentarios from Cliente where NumeroComentarios > 5 and NumeroComentarios < 10;"

In [ ]:
consulta_sql = cursor.execute(consulta).fetchall()

In [ ]:
consulta_sql

[('Carlos Souza', 8), ('Rafael Ferreira', 7)]

## operador `LIKE`

Exemplo 1

In [ ]:
consulta = "SELECT Nome from Cliente where Genero = \"Masculino\";"

In [ ]:
consulta_sql = cursor.execute(consulta).fetchall()

In [ ]:
consulta_sql

[('Carlos Souza',),
 ('Pedro Costa',),
 ('João Almeida',),
 ('Rafael Ferreira',),
 ('Luiz Mendes',)]

Exemplo 2

In [ ]:
consulta = "SELECT Nome from Cliente where Nome LIKE \"M%\";"

In [ ]:
consulta_sql = cursor.execute(consulta).fetchall()

In [ ]:
consulta_sql

[('Maria Oliveira',), ('Mariana Santos',)]

## Operador `IN`

In [ ]:
consulta = "SELECT TextoOriginal FROM Comentario where Avaliacao IN (5, 4);"

In [ ]:
consulta_sql = cursor.execute(consulta).fetchall()

In [ ]:
consulta_sql

[('Ótimo atendimento e comida deliciosa!',),
 ('Ambiente agradável e preços justos.',),
 ('Excelente variedade de pratos.',),
 ('Sobremesas maravilhosas!',),
 ('Ótima opção para vegetarianos.',),
 ('Música ao vivo excelente!',),
 ('Atendimento personalizado e simpático.',),
 ('Localização privilegiada e ambiente sofisticado.',),
 ('Carta de vinhos excepcional.',),
 ('Buffet variado e bem servido.',),
 ('Restaurante acessível para cadeirantes.',),
 ('Menu infantil muito bom.',),
 ('Serviço de reserva eficiente.',)]

# Operador `Order By`

A cláusula `order by` é usada para classificar o conjunto de resultados em ordem crescente ou decrescente.

Exemplo 1

In [ ]:
consulta = "SELECT Nome, NumeroComentarios from CLIENTE order by (NumeroComentarios);"

In [ ]:
consulta_sql = cursor.execute(consulta).fetchall()

In [ ]:
consulta_sql

[('Pedro Costa', 5),
 ('Rafael Ferreira', 7),
 ('Carlos Souza', 8),
 ('Fernanda Lima', 10),
 ('Mariana Santos', 12),
 ('Ana Silva', 15),
 ('João Almeida', 18),
 ('Patrícia Araujo', 20),
 ('Maria Oliveira', 22),
 ('Luiz Mendes', 25)]

Exemplo 2

In [ ]:
consulta = "SELECT Nome, NumeroComentarios from CLIENTE order by (Nome) DESC;"

In [ ]:
consulta_sql = cursor.execute(consulta).fetchall()

In [ ]:
consulta_sql

[('Rafael Ferreira', 7),
 ('Pedro Costa', 5),
 ('Patrícia Araujo', 20),
 ('Mariana Santos', 12),
 ('Maria Oliveira', 22),
 ('Luiz Mendes', 25),
 ('João Almeida', 18),
 ('Fernanda Lima', 10),
 ('Carlos Souza', 8),
 ('Ana Silva', 15)]

# Valores `NULL`

Os campos não preenchidos são representados pelo valor `NULL`.

Não é possível testar valores `NULL` com os operadores de comparação: `>`ou `=`.

É necessário usar os operadores `IS NULL` e `IS NOT NULL`.

In [ ]:
cliente11 = "INSERT INTO Cliente (IDCliente, Nome, NumeroComentarios, NumeroLikes, Localizacao, Genero) VALUES (11, 'Ana Silva', 15, 120, NULL, 'Feminino');"

In [ ]:
cursor.execute(cliente11)

In [ ]:
consulta = 'SELECT * FROM Cliente;'

In [ ]:
df_cliente = pd.read_sql_query(consulta, conexao)

In [ ]:
df_cliente

,IDCliente,Nome,NumeroComentarios,NumeroLikes,Localizacao,Genero
0,1,Ana Silva,15,120,São Paulo,Feminino
1,2,Carlos Souza,8,45,Rio de Janeiro,Masculino
2,3,Maria Oliveira,22,210,Belo Horizonte,Feminino
3,4,Pedro Costa,5,30,Curitiba,Masculino
4,5,Fernanda Lima,10,80,Porto Alegre,Feminino
5,6,João Almeida,18,150,Recife,Masculino
6,7,Mariana Santos,12,95,Salvador,Feminino
7,8,Rafael Ferreira,7,60,Brasília,Masculino
8,9,Patrícia Araujo,20,175,Fortaleza,Feminino
9,10,Luiz Mendes,25,200,Manaus,Masculino
10,11,Ana Silva,15,120,None,Feminino

# Atualização - `UPDATE`

A instrução `UPDATE` é usada para modificar os registros existentes em uma tabela.

In [ ]:
consulta = "UPDATE Cliente SET NumeroLikes = 100 where IDCliente = 5;"

In [ ]:
cursor.execute(consulta)

In [ ]:
consulta = 'SELECT * FROM Cliente;'
df_cliente = pd.read_sql_query(consulta, conexao)
df_cliente

,IDCliente,Nome,NumeroComentarios,NumeroLikes,Localizacao,Genero
0,1,Ana Silva,15,120,São Paulo,Feminino
1,2,Carlos Souza,8,45,Rio de Janeiro,Masculino
2,3,Maria Oliveira,22,210,Belo Horizonte,Feminino
3,4,Pedro Costa,5,30,Curitiba,Masculino
4,5,Fernanda Lima,10,100,Porto Alegre,Feminino
5,6,João Almeida,18,150,Recife,Masculino
6,7,Mariana Santos,12,95,Salvador,Feminino
7,8,Rafael Ferreira,7,60,Brasília,Masculino
8,9,Patrícia Araujo,20,175,Fortaleza,Feminino
9,10,Luiz Mendes,25,200,Manaus,Masculino
10,11,Ana Silva,15,120,None,Feminino

# Apagar dados - `DELETE`

A instrução `DELETE` é usada para apagar registros das tabelas.

In [ ]:
consulta = 'DELETE FROM Cliente WHERE IDCliente = 2;'

In [ ]:
cursor.execute(consulta)

In [ ]:
consulta = 'SELECT * FROM Cliente;'
df_cliente = pd.read_sql_query(consulta, conexao)
df_cliente

,IDCliente,Nome,NumeroComentarios,NumeroLikes,Localizacao,Genero
0,1,Ana Silva,15,120,São Paulo,Feminino
1,3,Maria Oliveira,22,210,Belo Horizonte,Feminino
2,4,Pedro Costa,5,30,Curitiba,Masculino
3,5,Fernanda Lima,10,100,Porto Alegre,Feminino
4,6,João Almeida,18,150,Recife,Masculino
5,7,Mariana Santos,12,95,Salvador,Feminino
6,8,Rafael Ferreira,7,60,Brasília,Masculino
7,9,Patrícia Araujo,20,175,Fortaleza,Feminino
8,10,Luiz Mendes,25,200,Manaus,Masculino
9,11,Ana Silva,15,120,None,Feminino

# Funções

O `SQL` possui um conjunto de funções que podem ser usadas durante as consultas ao banco de dados.

## `MAX` e `MIN`

In [ ]:
consulta = "SELECT Nome, MAX(NumeroComentarios) FROM Cliente;"

In [ ]:
cursor.execute(consulta)

In [ ]:
df_cliente = pd.read_sql_query(consulta, conexao)
df_cliente

          Nome  MAX(NumeroComentarios)
0  Luiz Mendes                      25

## `COUNT`, `AVG` e `SUM`

In [ ]:
consulta = "SELECT COUNT(*) FROM Comentario;"

In [ ]:
df_comentario = pd.read_sql_query(consulta, conexao)
df_comentario

   COUNT(*)
0        20

# Operador `Group By`

A instrução `Group By` agrupa as linhas que possuem os mesmos valores em linhas de resumo.

As instruções `Group By` são usualmente empregadas com funções agregadas (`MAX`, `MIN`, `COUNT`, `SUM`, `AVG`).

In [ ]:
consulta = "SELECT Genero, Count(*) FROM Cliente GROUP BY (Genero);"

In [ ]:
df_cliente = pd.read_sql_query(consulta, conexao)
df_cliente

      Genero  Count(*)
0   Feminino         6
1  Masculino         4

# Operador de Junção

Uma operação de junção é usada para combinar linhas de duas ou mais tabelas com base no relacionamento entre colunas.

In [ ]:
consulta = "SELECT CL.nome, CO.TextoOriginal FROM Cliente AS CL JOIN Comentario AS CO ON CL.IDCliente = CO.IDComentario;"

consulta = "SELECT CL.nome, CO.TextoOriginal FROM Cliente AS CL, Comentario AS CO where CL.IDCliente = CO.IDCliente;"

In [ ]:
df = pd.read_sql_query(consulta, conexao)
df.head()

             Nome                          TextoOriginal
0       Ana Silva  Ótimo atendimento e comida deliciosa!
1  Maria Oliveira      A comida estava fria e sem sabor.
2     Pedro Costa         Excelente variedade de pratos.
3   Fernanda Lima                 Demora no atendimento.
4    João Almeida               Sobremesas maravilhosas!